import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import vm from 'node:vm';

const html = await readFile(new URL('../multistreams.tv/multistreams.html', import.meta.url), 'utf8');
const backendClient = await readFile(new URL('../multistreams.tv/backend-client.js', import.meta.url), 'utf8');
const contactClient = await readFile(new URL('../multistreams.tv/contact.js', import.meta.url), 'utf8');
const oauthRoute = await readFile(new URL('../src/routes/oauth.js', import.meta.url), 'utf8');
const aiRoute = await readFile(new URL('../src/routes/ai.js', import.meta.url), 'utf8');
const platforms = await readFile(new URL('../src/platforms.js', import.meta.url), 'utf8');
const thirdPartyRoute = await readFile(new URL('../src/routes/third-party.js', import.meta.url), 'utf8');
const profileRoute = await readFile(new URL('../src/routes/profile.js', import.meta.url), 'utf8');
const authRoute = await readFile(new URL('../src/routes/auth.js', import.meta.url), 'utf8');
const messageRoute = await readFile(new URL('../src/routes/messages.js', import.meta.url), 'utf8');
const statusRoute = await readFile(new URL('../src/routes/status.js', import.meta.url), 'utf8');
const socialMigration = await readFile(new URL('../migrations/0003_social_messaging_youtube.sql', import.meta.url), 'utf8');
const worker = await readFile(new URL('../src/index.js', import.meta.url), 'utf8');
const wrangler = await readFile(new URL('../wrangler.jsonc', import.meta.url), 'utf8');

test('no provider API keys, OAuth bearer tokens, or Discord webhooks remain in frontend source', () => {
  assert.doesNotMatch(html, /AIza[0-9A-Za-z_-]{20,}/);
  assert.doesNotMatch(html, /discord\.com\/api\/webhooks\//);
  assert.doesNotMatch(html, /YB3lxGALkuaqHAf31EQcMwKfWlt1/);
  assert.doesNotMatch(html, /Bearer\s+[0-9a-z]{20,}/i);
  assert.doesNotMatch(backendClient, /x-goog-api-key|client_secret|discord\.com\/api\/webhooks\//i);
  assert.doesNotMatch(contactClient, /x-api-key|client_secret|discord\.com\/api\/webhooks\//i);
});

test('all inline classic scripts and the backend client parse as JavaScript', () => {
  const scripts = [...html.matchAll(/<script(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/gi)].map(match => match[1]);
  assert.ok(scripts.length > 0);
  scripts.forEach((source, index) => assert.doesNotThrow(() => new vm.Script(source, { filename: `multistreams-inline-${index}.js` })));
  assert.doesNotThrow(() => new vm.Script(backendClient, { filename: 'backend-client.js' }));
  assert.match(html, /<script src="\/backend-client\.js\?v=[0-9.]+"><\/script>/);
});

test('platform-aware UI fallbacks and category metadata rules are present', () => {
  assert.doesNotMatch(backendClient, /forceInitials \|\| item\?\.platform === 'kick'/);
  assert.match(backendClient, /suggested-platform-icon/);
  assert.match(backendClient, /hasViewerCount/);
  assert.match(backendClient, /\['kick', 'youtube'\]\.includes\(currentBrowsePlatform\)/);
  assert.doesNotMatch(backendClient, /Rumble did not recognize that Live Stream API URL/);
});

test('YouTube account connection reuses the Google profile OAuth entry point', () => {
  assert.match(backendClient, /\/api\/oauth\/google\/start\?purpose=youtube-connect&returnTo=\/multistreams/);
  assert.match(oauthRoute, /const GOOGLE_YOUTUBE_PURPOSE = 'youtube-connect'/);
  assert.match(oauthRoute, /fetchIdentity\(connectedPlatform, tokens\.access_token, env\)/);
  assert.match(oauthRoute, /destination\.searchParams\.set\('oauth', connectedPlatform\)/);
  assert.match(oauthRoute, /await saveConnection\(env, result\.user\.id, 'youtube'/);
  assert.match(oauthRoute, /return OAUTH\.youtube\.scopes/);
  assert.match(oauthRoute, /pendingConnection = await encrypt/);
  assert.match(authRoute, /await saveConnection\(env, challenge\.user_id, 'youtube'/);
  assert.doesNotMatch(html, /accounts\.google\.com\/gsi\/client|initTokenClient|response\.access_token/);
});

test('social messaging, notification history, profile panels, and status routes are wired', () => {
  assert.match(messageRoute, /INSERT INTO direct_messages/);
  assert.match(messageRoute, /Messaging is unavailable because one of these profiles is blocked/);
  assert.match(socialMigration, /CREATE TABLE IF NOT EXISTS conversations/);
  assert.match(socialMigration, /CREATE TABLE IF NOT EXISTS profile_panels/);
  assert.match(profileRoute, /\/api\/profile\/panels\/reorder/);
  assert.match(backendClient, /loadBackendNotifications\(\{ announce: true \}\)/);
  assert.match(backendClient, /backendNotificationId/);
  assert.match(html, /formatRelativeNotificationTime/);
  assert.match(html, /dark_theme=true/);
  assert.match(statusRoute, /UPTIMEROBOT_API_KEY/);
  assert.match(statusRoute, /UPTIMEROBOT_RESPONSE_API_KEY/);
  assert.match(statusRoute, /mergeUptimeRobotServices/);
  assert.match(worker, /shared_layout_banner\.png/);
});

test('production UI fixes remain wired to backend-normalized data', () => {
  assert.doesNotMatch(html, /id="ai-search-model"/);
  assert.match(html, /notificationsEnabled:\s*true/);
  assert.match(html, /uiSounds:\s*true/);
  assert.match(html, /data\.items\?\.find\(item => item\.platform === 'youtube'\)\?\.id/);
  assert.match(html, /data\.items\?\.\[0\]\?\.id \|\| null/);
  assert.match(backendClient, /parseProfileLayoutLink\(location\.href\)/);
  assert.match(backendClient, /\/api\/security\/devices\/\$\{encodeURIComponent\(deviceId\)\}/);
  assert.match(html, /AI_SEARCH_ICON\.png/);
  assert.match(html, /stream\.platform === 'youtube' && stream\.id \? stream\.id/);
  assert.match(backendClient, /videoId \|\| detail\.id \|\| detail\.username \|\| name/);
  assert.doesNotMatch(backendClient, /is not live on YouTube right now/);
  assert.match(html, /function liveNotificationIdentity/);
  assert.match(html, /function pruneDeletedLiveNotifications/);
  assert.match(html, /loadLiveNotifications\(\);\s*calculateNotificationCounts/);
  assert.doesNotMatch(html, /mockLiveStreamers = \[\];\s*deletedLiveNotifications = \[\]/);
  assert.match(html, /oninput="searchPrivacyBlockProfiles\(this\.value\)"/);
  assert.match(html, /id="privacy-block-search-results"/);
  assert.match(backendClient, /\/api\/profiles\?q=\$\{encodeURIComponent\(value\)\}/);
  assert.match(backendClient, /\/api\/profiles\/\$\{encodeURIComponent\(username\)\}\/block/);
  assert.match(backendClient, /async function loadBlockedProfiles/);
  assert.match(html, /\.suggested-card \.name \{[^}]*text-overflow: ellipsis;[^}]*white-space: nowrap;/);
  assert.match(backendClient, /class="name" title="\$\{escapeHTML\(user\.name\)\}"/);
  assert.match(html, /\.profile-more-control \{[^}]*margin-left: auto;[^}]*margin-right: 6px;/);
  assert.match(html, /class="profile-user-list-heading-icon"/);
  assert.match(backendClient, /profile-user-list-icon/);
  assert.match(html, /class="service-status-heading"/);
  assert.match(html, /class="service-status-title-icon"/);
  assert.match(backendClient, /service-status-incidents/);
  assert.match(html, /#service-status-modal \{ z-index: 12000 !important; \}/);
  assert.match(html, /\.service-status-pill::after/);
  assert.match(backendClient, /service-status-timeline/);
  assert.match(html, /id="sidebar-sort-toggle"/);
  assert.match(backendClient, /function sortSidebarItems/);
  assert.match(backendClient, /window\.toggleSort = \(\) =>/);
  assert.match(backendClient, /sortSidebarItems\(real\.recommendedCategories, item => item\.watching\)/);
  assert.match(html, /\.profile-about-social-icon svg/);
  assert.match(backendClient, /getPlatformIcon\(String\(platform\)\.toLowerCase\(\)\)/);
  assert.match(html, /id="profile-panel-delete"[^>]*profile-panel-delete-button[^>]*aria-label="Remove about panel"/);
  assert.match(html, /fa-trash-can/);
  assert.match(profileRoute, /SELECT u\.username, u\.avatar_url, u\.banner_url, u\.bio FROM profile_blocks/);
});

test('OAuth, AI recovery, YouTube data fallbacks, and share routes have regressions covered', () => {
  assert.match(wrangler, /"TWITCH_REDIRECT_URI":\s*"https:\/\/multistreams\.tv\/multistreams"/);
  assert.match(backendClient, /\/api\/oauth\/twitch\/callback\?\$\{oauthRelayParams\.toString\(\)\}/);
  assert.match(aiRoute, /MALFORMED_FUNCTION_CALL/);
  assert.match(aiRoute, /Do not emit or call any function/);
  assert.match(platforms, /\/subscriptions\?part=snippet&mine=true&maxResults=50&order=alphabetical/);
  assert.match(platforms, /while \(pageToken\)/);
  assert.match(platforms, /const discoverySize = Math\.min\(30, stored\.length\)/);
  assert.doesNotMatch(platforms, /slice\.map\(channelId => youtubeSearchVideos/);
  assert.match(platforms, /forHandle=/);
  assert.match(platforms, /if \(live && error\?\.code === 'youtube_rate_limited' && env\.SCRAPECREATORS_API_KEY\)/);
  assert.match(platforms, /\/search\?part=snippet&type=channel/);
  assert.match(thirdPartyRoute, /\/v1\/youtube\/shorts\/trending/);
  assert.match(thirdPartyRoute, /\/v1\/rumble\//);
  assert.match(oauthRoute, /Array\.isArray\(tokens\.scope\)/);
  assert.match(worker, /new URL\('\/api\/oauth\/twitch\/callback'/);
  assert.match(platforms, /appToken\(env, 'twitch', true\)/);
  assert.match(worker, /async function layoutShell/);
  assert.match(wrangler, /"run_worker_first":\s*\[[^\]]*"\/layout"/);
  assert.match(html, /function createLayoutShareLink/);
  assert.match(html, /async function hydrateLoadedLayoutChannels/);
  assert.match(html, /channels = await hydrateLoadedLayoutChannels\(streams\)/);
  assert.match(backendClient, /if \(!incomingSharedLayout\?\.streams\?\.length\) jobs\.push\(loadRemoteState\(\)\)/);
  assert.match(html, /-webkit-line-clamp:\s*2/);
  assert.match(html, /notificationsMarkedAsRead = false/);
  assert.match(html, /clip\.duration \? `<span class="browse-duration">/);
  assert.match(backendClient, /function browseMediaDuration\(item\)/);
  assert.match(backendClient, /card\.style\.position = 'fixed'/);
  assert.doesNotMatch(platforms, /sharedPublicLiveIndex/);
  assert.match(platforms, /if \(categoryId\) params\.set\('videoCategoryId', categoryId\)/);
  assert.match(platforms, /recordedDurationSeconds/);
  assert.match(platforms, /async function youtubeCreatorLiveFallback/);
  assert.match(platforms, /async function youtubeCreatorChannelDetail/);
  assert.match(platforms, /async function verifyCreatorYoutubeLiveCandidates/);
  assert.match(platforms, /if \(!isCreatorYoutubeLivePayload\(payload\)\) return null/);
  assert.doesNotMatch(platforms, /item\.concurrentViewersText \|\| item\.viewCountText/);
  assert.match(platforms, /creator:youtube:live:v3/);
  assert.match(platforms, /browse:v8/);
  assert.match(platforms, /categoryName \? `\$\{categoryName\} live`/);
  assert.match(platforms, /const streams = requestedVideo\s*\?\s*\(requestedVideo\.live \? \[requestedVideo\] : \[\]\)/);
  assert.match(platforms, /SCRAPECREATORS_API_KEY && error\?\.code === 'youtube_rate_limited'/);
  assert.match(platforms, /async function kickUsers/);
  assert.match(platforms, /async function kickChannelDetail/);
  assert.match(platforms, /broadcaster_user/);
  assert.match(platforms, /profile_picture/);
  assert.match(platforms, /appToken\(env, 'kick', true\)/);
  assert.match(backendClient, /avatar: item\.avatar \|\| ''/);
  assert.match(backendClient, /hasViewerCount\(detail\)/);
  assert.doesNotMatch(html, /enteringGrid[\s\S]{0,500}player\.kick\.com/);
  assert.match(platforms, /featured:last-good:v1/);
  assert.match(platforms, /ranked\.length < minimumHealthySize/);
  assert.match(platforms, /cacheGetStale\(env, lastGoodKey, 300\)/);
  assert.match(platforms, /searchRumbleChannels\(env, 'live'/);
  assert.match(platforms, /const platformOrder = \['twitch', 'youtube', 'kick', 'rumble'\]/);
  assert.match(platforms, /_liveResult: true/);
  assert.match(backendClient, /function balanceSidebarPlatforms/);
  assert.match(backendClient, /balanceSidebarPlatforms\(real\.featured, item => item\.viewers\)/);
  assert.match(html, /\.sidebar-show-toggle \{[^}]*color: var\(--accent\);/);
  assert.match(html, /\.suggested-name-row \{[^}]*width: fit-content;/);
  assert.match(html, /\.profile-media-grid > \.browse-clip-grid \{[^}]*grid-template-columns: repeat\(4,/);
  assert.match(platforms, /if \(!broadcasterId\) \{\s*params\.set\('started_at'/);
  assert.match(platforms, /youtubeChannelVideosBySearch/);
  assert.match(platforms, /fallbackUsername = ''/);
  assert.match(profileRoute, /profilePlatformHint\(platform, social\?\.url\)/);
});
